/* Auto-generated by tools/gen_lcd_positions.py — mesh LCD bounds + mask anchor */
#ifndef CUPCAKE_SPRITE_LCD_H_
#define CUPCAKE_SPRITE_LCD_H_

#include "cupcake_sprites.h"

typedef struct {
    const char *name;
    int lcd_x, lcd_y;
} cupcake_sprite_lcd_t;

/* Atlas Y of marge1 body top before hair was included in the sprite rect. */
#define CUPCAKE_MARGE1_LEGACY_ATLAS_Y 147

/* Header/auto only: keep hair inside LCD when lcd_y is from cupcake_sprite_lcd.h. */
static inline int cupcake_sprite_lcd_resolve_y(const char *name, int lcd_y)
{
    const cupcake_sprite_rect_t *spr;
    int hair_rows;
    int min_y;

    if (!name || name[0] != 'm' || name[1] != 'a' || name[2] != 'r' || name[3] != 'g' ||
        name[4] != 'e' || name[5] != '1' || name[6])
        return lcd_y;
    spr = cupcake_sprite_by_name(name);
    if (!spr)
        return lcd_y;
    hair_rows = CUPCAKE_MARGE1_LEGACY_ATLAS_Y - spr->y;
    if (hair_rows <= 0)
        return lcd_y;
    min_y = 1 - hair_rows;
    if (lcd_y < min_y)
        return min_y;
    return lcd_y;
}
static const cupcake_sprite_lcd_t cupcake_sprite_lcd[] = {
    { "bart0", 26, 540 },
    { "bart1", 110, 443 },
    { "bart2", 235, 368 },
    { "bart3", 360, 395 },
    { "bart4", 485, 482 },
    { "bart5", 585, 382 },
    { "bart6", 490, 9 },
    { "bart7", 116, 395 },
    { "bart8", 514, 430 },
    { "bart9", 167, 650 },
    { "cake0", 55, 690 },
    { "cake01", 20, 495 },
    { "cake02", 93, 495 },
    { "cake03", 57, 475 },
    { "cake04", 84, 447 },
    { "cake05", 49, 435 },
    { "cake1", 219, 209 },
    { "cake11", 123, 355 },
    { "cake12", 175, 358 },
    { "cake13", 178, 310 },
    { "cake14", 133, 310 },
    { "cake15", 160, 265 },
    { "cake2", 334, 211 },
    { "cake21", 231, 327 },
    { "cake22", 286, 341 },
    { "cake23", 300, 291 },
    { "cake24", 241, 290 },
    { "cake25", 281, 250 },
    { "cake3", 452, 202 },
    { "cake31", 382, 363 },
    { "cake32", 448, 368 },
    { "cake33", 453, 314 },
    { "cake34", 400, 321 },
    { "cake35", 422, 273 },
    { "cake4", 503, 242 },
    { "cake41", 516, 402 },
    { "cake42", 567, 401 },
    { "cake43", 556, 348 },
    { "cake44", 509, 354 },
    { "cake45", 519, 307 },
    { "cake5", 282, 129 },
    { "cake6", 397, 134 },
    { "cake7", 512, 122 },
    { "cake8", 619, 115 },
    { "cake9", 445, 690 },
    { "couch0", 758, 108 },
    { "couch1", 816, 355 },
    { "couch2", 755, 335 },
    { "couch3", 621, 598 },
    { "couch4", 726, 485 },
    { "digit00", 936, 25 },
    { "digit01", 959, 26 },
    { "digit03", 958, 67 },
    { "digit04", 932, 78 },
    { "digit05", 929, 66 },
    { "digit06", 932, 22 },
    { "digit10", 876, 23 },
    { "digit11", 900, 26 },
    { "digit13", 899, 67 },
    { "digit14", 874, 77 },
    { "digit15", 871, 66 },
    { "digit16", 872, 20 },
    { "digit20", 820, 24 },
    { "digit21", 842, 26 },
    { "digit22", 826, 52 },
    { "digit23", 841, 67 },
    { "digit24", 817, 78 },
    { "digit25", 815, 66 },
    { "digit26", 816, 20 },
    { "digit30", 762, 23 },
    { "digit31", 784, 26 },
    { "digit32", 766, 52 },
    { "digit33", 783, 67 },
    { "digit34", 760, 78 },
    { "digit35", 756, 66 },
    { "digit36", 758, 20 },
    { "digit40", 701, 21 },
    { "digit41", 726, 26 },
    { "digit42", 708, 53 },
    { "digit43", 725, 67 },
    { "digit44", 701, 78 },
    { "digit45", 697, 66 },
    { "digit46", 699, 18 },
    { "maggie0", 705, 243 },
    { "maggie1", 724, 267 },
    { "maggie2", 855, 253 },
    { "maggie3", 720, 192 },
    { "marge1", 0, 115 },
    { "miss1", 20, 5 },
    { "miss2", 98, 5 },
    { "miss3", 175, 5 },
    { "pacifier1", 434, 149 },
    { "pacifier2", 343, 252 },
};

#define CUPCAKE_SPRITE_LCD_COUNT 93

static inline const cupcake_sprite_lcd_t *cupcake_sprite_lcd_by_name(const char *name) {
    for (unsigned i = 0; i < CUPCAKE_SPRITE_LCD_COUNT; i++) {
        const char *a = cupcake_sprite_lcd[i].name, *b = name;
        while (*a && *b && *a == *b) { a++; b++; }
        if (!*a && !*b) return &cupcake_sprite_lcd[i];
    }
    return 0;
}

#endif
