/* Auto-generated by tools/gen_sprites.py — triangle raster from sprites.json */
/* Blit: sprites-color.png + per-sprite mask in cupcake_sprite_masks.h */
#ifndef CUPCAKE_SPRITES_H_
#define CUPCAKE_SPRITES_H_

#define CUPCAKE_ATLAS_W 1024
#define CUPCAKE_ATLAS_H 1024

typedef struct {
    const char *name;
    int x, y, w, h;
} cupcake_sprite_rect_t;

static const cupcake_sprite_rect_t cupcake_sprites[] = {
    { "bart0", 25, 538, 125, 67 },
    { "bart1", 109, 440, 137, 244 },
    { "bart2", 234, 366, 120, 274 },
    { "bart3", 360, 388, 139, 279 },
    { "bart4", 481, 479, 117, 251 },
    { "bart5", 582, 378, 163, 237 },
    { "bart6", 485, 11, 239, 412 },
    { "bart7", 114, 393, 98, 77 },
    { "bart8", 514, 428, 99, 48 },
    { "bart9", 167, 650, 290, 105 },
    { "cake0", 59, 689, 94, 66 },
    { "cake01", 25, 494, 38, 41 },
    { "cake02", 90, 498, 38, 42 },
    { "cake03", 57, 480, 38, 40 },
    { "cake04", 80, 452, 42, 41 },
    { "cake05", 46, 437, 39, 40 },
    { "cake1", 213, 201, 46, 48 },
    { "cake11", 123, 352, 45, 45 },
    { "cake12", 169, 355, 45, 43 },
    { "cake13", 175, 310, 42, 45 },
    { "cake14", 134, 307, 42, 45 },
    { "cake15", 160, 269, 45, 46 },
    { "cake2", 339, 187, 45, 45 },
    { "cake21", 237, 325, 49, 47 },
    { "cake22", 283, 329, 44, 45 },
    { "cake23", 297, 287, 43, 45 },
    { "cake24", 249, 282, 48, 45 },
    { "cake25", 278, 245, 45, 46 },
    { "cake3", 451, 183, 45, 47 },
    { "cake31", 392, 355, 43, 44 },
    { "cake32", 435, 354, 45, 45 },
    { "cake33", 445, 312, 43, 45 },
    { "cake34", 407, 314, 43, 44 },
    { "cake35", 418, 270, 46, 48 },
    { "cake4", 510, 245, 43, 44 },
    { "cake41", 522, 389, 42, 44 },
    { "cake42", 562, 388, 49, 48 },
    { "cake43", 551, 346, 49, 46 },
    { "cake44", 511, 344, 44, 47 },
    { "cake45", 529, 305, 44, 44 },
    { "cake5", 300, 136, 46, 44 },
    { "cake6", 402, 112, 44, 46 },
    { "cake7", 510, 113, 45, 44 },
    { "cake8", 618, 103, 45, 44 },
    { "cake9", 444, 690, 86, 73 },
    { "couch0", 754, 111, 257, 122 },
    { "couch1", 812, 355, 212, 388 },
    { "couch2", 753, 335, 176, 402 },
    { "couch3", 617, 599, 110, 148 },
    { "couch4", 723, 485, 103, 217 },
    { "digit00", 937, 22, 41, 21 },
    { "digit01", 963, 29, 20, 33 },
    { "digit03", 961, 60, 19, 33 },
    { "digit04", 933, 79, 40, 20 },
    { "digit05", 926, 59, 22, 35 },
    { "digit06", 929, 26, 21, 36 },
    { "digit10", 879, 22, 42, 21 },
    { "digit11", 905, 29, 21, 33 },
    { "digit13", 903, 60, 20, 33 },
    { "digit14", 875, 79, 41, 20 },
    { "digit15", 868, 59, 22, 35 },
    { "digit16", 871, 26, 21, 36 },
    { "digit20", 822, 22, 41, 21 },
    { "digit21", 847, 29, 21, 33 },
    { "digit22", 825, 50, 29, 21 },
    { "digit23", 845, 60, 20, 33 },
    { "digit24", 818, 79, 40, 20 },
    { "digit25", 811, 59, 21, 35 },
    { "digit26", 814, 25, 20, 37 },
    { "digit30", 764, 22, 41, 21 },
    { "digit31", 790, 29, 20, 33 },
    { "digit32", 767, 50, 30, 21 },
    { "digit33", 788, 60, 19, 33 },
    { "digit34", 760, 79, 41, 20 },
    { "digit35", 753, 59, 22, 35 },
    { "digit36", 756, 26, 21, 36 },
    { "digit40", 705, 22, 42, 21 },
    { "digit41", 731, 29, 21, 33 },
    { "digit42", 708, 50, 30, 21 },
    { "digit43", 729, 60, 20, 33 },
    { "digit44", 701, 79, 41, 20 },
    { "digit45", 694, 59, 22, 35 },
    { "digit46", 698, 26, 20, 36 },
    { "maggie0", 705, 240, 159, 233 },
    { "maggie1", 725, 262, 43, 43 },
    { "maggie2", 852, 247, 114, 71 },
    { "maggie3", 722, 190, 146, 73 },
    { "marge1", 0, 116, 271, 390 },
    { "miss1", 22, 7, 77, 96 },
    { "miss2", 100, 7, 76, 96 },
    { "miss3", 175, 7, 258, 96 },
    { "pacifier1", 396, 150, 129, 62 },
    { "pacifier2", 329, 263, 67, 105 },
};

#define CUPCAKE_SPRITE_COUNT 93

static inline const cupcake_sprite_rect_t *cupcake_sprite_by_name(const char *name) {
    for (unsigned i = 0; i < CUPCAKE_SPRITE_COUNT; i++) {
        const char *a = cupcake_sprites[i].name, *b = name;
        while (*a && *b && *a == *b) { a++; b++; }
        if (!*a && !*b) return &cupcake_sprites[i];
    }
    return 0;
}

#endif
