/* Auto-generated by tools/gen_demo_data.py from game/demo.model */
#ifndef CUPCAKE_DEMO_H_
#define CUPCAKE_DEMO_H_

#define CUPCAKE_DEMO_RATE_SEC 0.25
#define CUPCAKE_DEMO_FRAME_COUNT 163
#define CUPCAKE_DEMO_NAME_COUNT 45

static const char *const cupcake_demo_name_table[] = {
    "bart0",
    "bart1",
    "bart2",
    "bart3",
    "bart4",
    "bart5",
    "bart7",
    "bart8",
    "cake01",
    "cake02",
    "cake03",
    "cake04",
    "cake1",
    "cake11",
    "cake12",
    "cake13",
    "cake14",
    "cake21",
    "cake22",
    "cake23",
    "cake24",
    "cake3",
    "cake31",
    "cake32",
    "cake33",
    "cake34",
    "cake4",
    "cake41",
    "cake42",
    "cake43",
    "cake44",
    "cake5",
    "cake6",
    "cake7",
    "cake8",
    "couch0",
    "couch1",
    "couch2",
    "maggie0",
    "maggie1",
    "maggie2",
    "maggie3",
    "marge1",
    "pacifier1",
    "pacifier2",
};

typedef struct {
    const unsigned char *sprite_ids;
    unsigned char count;
} cupcake_demo_frame_t;

/* Per-frame sprite name indices into cupcake_demo_name_table */
static const unsigned char cupcake_demo_ids_0[] = { 2, 38 };
static const unsigned char cupcake_demo_ids_1[] = { 2, 38 };
static const unsigned char cupcake_demo_ids_2[] = { 2, 38 };
static const unsigned char cupcake_demo_ids_3[] = { 2, 38, 39 };
static const unsigned char cupcake_demo_ids_4[] = { 2, 38, 39 };
static const unsigned char cupcake_demo_ids_5[] = { 2, 38, 39 };
static const unsigned char cupcake_demo_ids_6[] = { 2, 38, 39 };
static const unsigned char cupcake_demo_ids_7[] = { 2, 38, 40 };
static const unsigned char cupcake_demo_ids_8[] = { 3, 38, 40 };
static const unsigned char cupcake_demo_ids_9[] = { 3, 38, 40 };
static const unsigned char cupcake_demo_ids_10[] = { 3, 38, 40 };
static const unsigned char cupcake_demo_ids_11[] = { 3, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_12[] = { 3, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_13[] = { 3, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_14[] = { 3, 34, 38 };
static const unsigned char cupcake_demo_ids_15[] = { 3, 33, 38 };
static const unsigned char cupcake_demo_ids_16[] = { 3, 33, 38 };
static const unsigned char cupcake_demo_ids_17[] = { 3, 33, 38 };
static const unsigned char cupcake_demo_ids_18[] = { 3, 33, 38 };
static const unsigned char cupcake_demo_ids_19[] = { 3, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_20[] = { 3, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_21[] = { 2, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_22[] = { 2, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_23[] = { 2, 22, 38, 40 };
static const unsigned char cupcake_demo_ids_24[] = { 3, 22, 38, 40 };
static const unsigned char cupcake_demo_ids_25[] = { 3, 22, 38, 40 };
static const unsigned char cupcake_demo_ids_26[] = { 3, 22, 38, 40 };
static const unsigned char cupcake_demo_ids_27[] = { 3, 22, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_28[] = { 2, 17, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_29[] = { 2, 17, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_30[] = { 2, 17, 34, 38 };
static const unsigned char cupcake_demo_ids_31[] = { 2, 17, 33, 38 };
static const unsigned char cupcake_demo_ids_32[] = { 1, 6, 13, 33, 38 };
static const unsigned char cupcake_demo_ids_33[] = { 1, 6, 13, 33, 38 };
static const unsigned char cupcake_demo_ids_34[] = { 2, 17, 33, 38 };
static const unsigned char cupcake_demo_ids_35[] = { 2, 17, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_36[] = { 2, 17, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_37[] = { 2, 17, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_38[] = { 3, 22, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_39[] = { 3, 22, 23, 38, 40 };
static const unsigned char cupcake_demo_ids_40[] = { 3, 22, 23, 38, 40 };
static const unsigned char cupcake_demo_ids_41[] = { 3, 22, 23, 38, 40 };
static const unsigned char cupcake_demo_ids_42[] = { 3, 22, 23, 38, 40 };
static const unsigned char cupcake_demo_ids_43[] = { 3, 22, 23, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_44[] = { 3, 22, 23, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_45[] = { 4, 7, 27, 28, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_46[] = { 4, 7, 27, 28, 34, 38 };
static const unsigned char cupcake_demo_ids_47[] = { 4, 7, 27, 28, 33, 38 };
static const unsigned char cupcake_demo_ids_48[] = { 4, 7, 27, 28, 33, 38 };
static const unsigned char cupcake_demo_ids_49[] = { 3, 22, 23, 33, 38 };
static const unsigned char cupcake_demo_ids_50[] = { 3, 22, 23, 33, 38 };
static const unsigned char cupcake_demo_ids_51[] = { 3, 22, 23, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_52[] = { 3, 22, 23, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_53[] = { 3, 22, 23, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_54[] = { 3, 22, 23, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_55[] = { 3, 22, 23, 24, 38, 40 };
static const unsigned char cupcake_demo_ids_56[] = { 3, 22, 23, 24, 38, 40 };
static const unsigned char cupcake_demo_ids_57[] = { 3, 22, 23, 24, 38, 40 };
static const unsigned char cupcake_demo_ids_58[] = { 2, 17, 18, 19, 38, 40 };
static const unsigned char cupcake_demo_ids_59[] = { 2, 17, 18, 19, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_60[] = { 2, 17, 18, 19, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_61[] = { 2, 17, 18, 19, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_62[] = { 2, 17, 18, 19, 34, 38 };
static const unsigned char cupcake_demo_ids_63[] = { 1, 6, 13, 14, 15, 33, 38, 43 };
static const unsigned char cupcake_demo_ids_64[] = { 1, 6, 13, 14, 15, 33, 38, 43 };
static const unsigned char cupcake_demo_ids_65[] = { 2, 17, 18, 19, 33, 38, 43 };
static const unsigned char cupcake_demo_ids_66[] = { 2, 17, 18, 19, 33, 38, 43 };
static const unsigned char cupcake_demo_ids_67[] = { 2, 17, 18, 19, 21, 38, 39, 42, 44 };
static const unsigned char cupcake_demo_ids_68[] = { 2, 17, 18, 19, 21, 38, 39, 42, 44 };
static const unsigned char cupcake_demo_ids_69[] = { 2, 17, 18, 19, 21, 38, 39, 42, 44 };
static const unsigned char cupcake_demo_ids_70[] = { 3, 22, 23, 24, 21, 38, 39, 42 };
static const unsigned char cupcake_demo_ids_71[] = { 3, 22, 23, 24, 25, 38, 40, 42 };
static const unsigned char cupcake_demo_ids_72[] = { 3, 22, 23, 24, 25, 38, 40, 42 };
static const unsigned char cupcake_demo_ids_73[] = { 3, 22, 23, 24, 25, 38, 40, 42 };
static const unsigned char cupcake_demo_ids_74[] = { 2, 17, 18, 19, 20, 38, 40, 42 };
static const unsigned char cupcake_demo_ids_75[] = { 1, 6, 13, 14, 15, 16, 34, 38, 41, 42 };
static const unsigned char cupcake_demo_ids_76[] = { 1, 0, 8, 9, 10, 11, 34, 38, 41, 42 };
static const unsigned char cupcake_demo_ids_77[] = { 1, 0, 8, 9, 10, 11, 34, 38, 41, 42 };
static const unsigned char cupcake_demo_ids_78[] = { 1, 0, 8, 9, 10, 11, 34, 38, 42 };
static const unsigned char cupcake_demo_ids_79[] = { 1, 0, 33, 38 };
static const unsigned char cupcake_demo_ids_80[] = { 1, 0, 33, 38 };
static const unsigned char cupcake_demo_ids_81[] = { 1, 6, 33, 38 };
static const unsigned char cupcake_demo_ids_82[] = { 1, 6, 33, 38 };
static const unsigned char cupcake_demo_ids_83[] = { 1, 6, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_84[] = { 2, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_85[] = { 2, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_86[] = { 3, 21, 38, 39 };
static const unsigned char cupcake_demo_ids_87[] = { 3, 22, 38, 40 };
static const unsigned char cupcake_demo_ids_88[] = { 3, 22, 38, 40 };
static const unsigned char cupcake_demo_ids_89[] = { 3, 22, 38, 40 };
static const unsigned char cupcake_demo_ids_90[] = { 3, 22, 38, 40 };
static const unsigned char cupcake_demo_ids_91[] = { 2, 17, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_92[] = { 2, 17, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_93[] = { 2, 17, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_94[] = { 2, 17, 34, 38 };
static const unsigned char cupcake_demo_ids_95[] = { 2, 17, 33, 38 };
static const unsigned char cupcake_demo_ids_96[] = { 2, 17, 33, 38 };
static const unsigned char cupcake_demo_ids_97[] = { 2, 17, 33, 38 };
static const unsigned char cupcake_demo_ids_98[] = { 2, 17, 33, 38 };
static const unsigned char cupcake_demo_ids_99[] = { 3, 22, 32, 38, 39, 36, 35 };
static const unsigned char cupcake_demo_ids_100[] = { 3, 22, 32, 38, 39, 36, 35 };
static const unsigned char cupcake_demo_ids_101[] = { 3, 22, 32, 38, 39, 36, 35 };
static const unsigned char cupcake_demo_ids_102[] = { 2, 17, 32, 38, 39, 36, 35 };
static const unsigned char cupcake_demo_ids_103[] = { 2, 17, 31, 38, 40, 36, 35 };
static const unsigned char cupcake_demo_ids_104[] = { 3, 22, 31, 38, 40, 36, 35 };
static const unsigned char cupcake_demo_ids_105[] = { 3, 22, 31, 38, 40, 36, 35 };
static const unsigned char cupcake_demo_ids_106[] = { 2, 17, 31, 38, 40, 36, 35 };
static const unsigned char cupcake_demo_ids_107[] = { 2, 17, 12, 34, 38, 41, 36, 35 };
static const unsigned char cupcake_demo_ids_108[] = { 1, 6, 13, 12, 34, 38, 41, 36, 35 };
static const unsigned char cupcake_demo_ids_109[] = { 1, 6, 13, 12, 34, 38, 41, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_110[] = { 1, 6, 13, 12, 34, 38, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_111[] = { 1, 6, 13, 14, 26, 38, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_112[] = { 1, 6, 13, 14, 26, 38, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_113[] = { 2, 17, 18, 26, 38, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_114[] = { 2, 17, 18, 26, 38, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_115[] = { 3, 22, 23, 27, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_116[] = { 4, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_117[] = { 4, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_118[] = { 4, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_119[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_120[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_121[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_122[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_123[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_124[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_125[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_126[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_127[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_128[] = { 5, 7, 27, 28, 29, 38, 39, 36, 37, 35 };
static const unsigned char cupcake_demo_ids_129[] = { 5, 7, 27, 28, 29, 38, 39 };
static const unsigned char cupcake_demo_ids_130[] = { 5, 7, 27, 28, 29, 38, 39 };
static const unsigned char cupcake_demo_ids_131[] = { 5, 7, 27, 28, 29, 38, 40 };
static const unsigned char cupcake_demo_ids_132[] = { 4, 7, 27, 28, 29, 38, 40 };
static const unsigned char cupcake_demo_ids_133[] = { 4, 7, 27, 28, 29, 38, 40 };
static const unsigned char cupcake_demo_ids_134[] = { 4, 7, 27, 28, 29, 38, 40 };
static const unsigned char cupcake_demo_ids_135[] = { 4, 7, 27, 28, 29, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_136[] = { 3, 22, 23, 24, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_137[] = { 3, 22, 23, 24, 34, 38, 41 };
static const unsigned char cupcake_demo_ids_138[] = { 3, 22, 23, 24, 34, 38 };
static const unsigned char cupcake_demo_ids_139[] = { 2, 17, 18, 19, 26, 38 };
static const unsigned char cupcake_demo_ids_140[] = { 2, 17, 18, 19, 26, 38 };
static const unsigned char cupcake_demo_ids_141[] = { 2, 17, 18, 19, 26, 38 };
static const unsigned char cupcake_demo_ids_142[] = { 3, 22, 23, 24, 26, 38 };
static const unsigned char cupcake_demo_ids_143[] = { 4, 7, 27, 28, 29, 30, 38, 39, 43 };
static const unsigned char cupcake_demo_ids_144[] = { 4, 7, 27, 28, 29, 30, 38, 39, 43 };
static const unsigned char cupcake_demo_ids_145[] = { 4, 7, 27, 28, 29, 30, 38, 39, 43 };
static const unsigned char cupcake_demo_ids_146[] = { 3, 22, 23, 24, 25, 38, 39, 43 };
static const unsigned char cupcake_demo_ids_147[] = { 3, 22, 23, 24, 25, 38, 40, 44 };
static const unsigned char cupcake_demo_ids_148[] = { 2, 17, 18, 19, 20, 38, 40, 44 };
static const unsigned char cupcake_demo_ids_149[] = { 2, 17, 18, 19, 20, 38, 40, 44 };
static const unsigned char cupcake_demo_ids_150[] = { 2, 17, 18, 19, 20, 38, 40, 44 };
static const unsigned char cupcake_demo_ids_151[] = { 2, 17, 18, 19, 20, 38, 41, 42 };
static const unsigned char cupcake_demo_ids_152[] = { 2, 17, 18, 19, 20, 38, 41, 42 };
static const unsigned char cupcake_demo_ids_153[] = { 2, 17, 18, 19, 20, 38, 41, 42 };
static const unsigned char cupcake_demo_ids_154[] = { 1, 6, 13, 14, 15, 16, 38, 42 };
static const unsigned char cupcake_demo_ids_155[] = { 1, 0, 8, 9, 10, 11, 38, 42 };
static const unsigned char cupcake_demo_ids_156[] = { 1, 0, 8, 9, 10, 11, 38, 42 };
static const unsigned char cupcake_demo_ids_157[] = { 1, 0, 38 };
static const unsigned char cupcake_demo_ids_158[] = { 1, 0, 38 };
static const unsigned char cupcake_demo_ids_159[] = { 1, 0, 38 };
static const unsigned char cupcake_demo_ids_160[] = { 1, 6, 38 };
static const unsigned char cupcake_demo_ids_161[] = { 1, 6, 38 };
static const unsigned char cupcake_demo_ids_162[] = { 2, 38 };

static const cupcake_demo_frame_t cupcake_demo_frames[] = {
    { cupcake_demo_ids_0, 2 },
    { cupcake_demo_ids_1, 2 },
    { cupcake_demo_ids_2, 2 },
    { cupcake_demo_ids_3, 3 },
    { cupcake_demo_ids_4, 3 },
    { cupcake_demo_ids_5, 3 },
    { cupcake_demo_ids_6, 3 },
    { cupcake_demo_ids_7, 3 },
    { cupcake_demo_ids_8, 3 },
    { cupcake_demo_ids_9, 3 },
    { cupcake_demo_ids_10, 3 },
    { cupcake_demo_ids_11, 4 },
    { cupcake_demo_ids_12, 4 },
    { cupcake_demo_ids_13, 4 },
    { cupcake_demo_ids_14, 3 },
    { cupcake_demo_ids_15, 3 },
    { cupcake_demo_ids_16, 3 },
    { cupcake_demo_ids_17, 3 },
    { cupcake_demo_ids_18, 3 },
    { cupcake_demo_ids_19, 4 },
    { cupcake_demo_ids_20, 4 },
    { cupcake_demo_ids_21, 4 },
    { cupcake_demo_ids_22, 4 },
    { cupcake_demo_ids_23, 4 },
    { cupcake_demo_ids_24, 4 },
    { cupcake_demo_ids_25, 4 },
    { cupcake_demo_ids_26, 4 },
    { cupcake_demo_ids_27, 5 },
    { cupcake_demo_ids_28, 5 },
    { cupcake_demo_ids_29, 5 },
    { cupcake_demo_ids_30, 4 },
    { cupcake_demo_ids_31, 4 },
    { cupcake_demo_ids_32, 5 },
    { cupcake_demo_ids_33, 5 },
    { cupcake_demo_ids_34, 4 },
    { cupcake_demo_ids_35, 5 },
    { cupcake_demo_ids_36, 5 },
    { cupcake_demo_ids_37, 5 },
    { cupcake_demo_ids_38, 5 },
    { cupcake_demo_ids_39, 5 },
    { cupcake_demo_ids_40, 5 },
    { cupcake_demo_ids_41, 5 },
    { cupcake_demo_ids_42, 5 },
    { cupcake_demo_ids_43, 6 },
    { cupcake_demo_ids_44, 6 },
    { cupcake_demo_ids_45, 7 },
    { cupcake_demo_ids_46, 6 },
    { cupcake_demo_ids_47, 6 },
    { cupcake_demo_ids_48, 6 },
    { cupcake_demo_ids_49, 5 },
    { cupcake_demo_ids_50, 5 },
    { cupcake_demo_ids_51, 6 },
    { cupcake_demo_ids_52, 6 },
    { cupcake_demo_ids_53, 6 },
    { cupcake_demo_ids_54, 6 },
    { cupcake_demo_ids_55, 6 },
    { cupcake_demo_ids_56, 6 },
    { cupcake_demo_ids_57, 6 },
    { cupcake_demo_ids_58, 6 },
    { cupcake_demo_ids_59, 7 },
    { cupcake_demo_ids_60, 7 },
    { cupcake_demo_ids_61, 7 },
    { cupcake_demo_ids_62, 6 },
    { cupcake_demo_ids_63, 8 },
    { cupcake_demo_ids_64, 8 },
    { cupcake_demo_ids_65, 7 },
    { cupcake_demo_ids_66, 7 },
    { cupcake_demo_ids_67, 9 },
    { cupcake_demo_ids_68, 9 },
    { cupcake_demo_ids_69, 9 },
    { cupcake_demo_ids_70, 8 },
    { cupcake_demo_ids_71, 8 },
    { cupcake_demo_ids_72, 8 },
    { cupcake_demo_ids_73, 8 },
    { cupcake_demo_ids_74, 8 },
    { cupcake_demo_ids_75, 10 },
    { cupcake_demo_ids_76, 10 },
    { cupcake_demo_ids_77, 10 },
    { cupcake_demo_ids_78, 9 },
    { cupcake_demo_ids_79, 4 },
    { cupcake_demo_ids_80, 4 },
    { cupcake_demo_ids_81, 4 },
    { cupcake_demo_ids_82, 4 },
    { cupcake_demo_ids_83, 5 },
    { cupcake_demo_ids_84, 4 },
    { cupcake_demo_ids_85, 4 },
    { cupcake_demo_ids_86, 4 },
    { cupcake_demo_ids_87, 4 },
    { cupcake_demo_ids_88, 4 },
    { cupcake_demo_ids_89, 4 },
    { cupcake_demo_ids_90, 4 },
    { cupcake_demo_ids_91, 5 },
    { cupcake_demo_ids_92, 5 },
    { cupcake_demo_ids_93, 5 },
    { cupcake_demo_ids_94, 4 },
    { cupcake_demo_ids_95, 4 },
    { cupcake_demo_ids_96, 4 },
    { cupcake_demo_ids_97, 4 },
    { cupcake_demo_ids_98, 4 },
    { cupcake_demo_ids_99, 7 },
    { cupcake_demo_ids_100, 7 },
    { cupcake_demo_ids_101, 7 },
    { cupcake_demo_ids_102, 7 },
    { cupcake_demo_ids_103, 7 },
    { cupcake_demo_ids_104, 7 },
    { cupcake_demo_ids_105, 7 },
    { cupcake_demo_ids_106, 7 },
    { cupcake_demo_ids_107, 8 },
    { cupcake_demo_ids_108, 9 },
    { cupcake_demo_ids_109, 10 },
    { cupcake_demo_ids_110, 9 },
    { cupcake_demo_ids_111, 9 },
    { cupcake_demo_ids_112, 9 },
    { cupcake_demo_ids_113, 8 },
    { cupcake_demo_ids_114, 8 },
    { cupcake_demo_ids_115, 9 },
    { cupcake_demo_ids_116, 10 },
    { cupcake_demo_ids_117, 10 },
    { cupcake_demo_ids_118, 10 },
    { cupcake_demo_ids_119, 10 },
    { cupcake_demo_ids_120, 10 },
    { cupcake_demo_ids_121, 10 },
    { cupcake_demo_ids_122, 10 },
    { cupcake_demo_ids_123, 10 },
    { cupcake_demo_ids_124, 10 },
    { cupcake_demo_ids_125, 10 },
    { cupcake_demo_ids_126, 10 },
    { cupcake_demo_ids_127, 10 },
    { cupcake_demo_ids_128, 10 },
    { cupcake_demo_ids_129, 7 },
    { cupcake_demo_ids_130, 7 },
    { cupcake_demo_ids_131, 7 },
    { cupcake_demo_ids_132, 7 },
    { cupcake_demo_ids_133, 7 },
    { cupcake_demo_ids_134, 7 },
    { cupcake_demo_ids_135, 8 },
    { cupcake_demo_ids_136, 7 },
    { cupcake_demo_ids_137, 7 },
    { cupcake_demo_ids_138, 6 },
    { cupcake_demo_ids_139, 6 },
    { cupcake_demo_ids_140, 6 },
    { cupcake_demo_ids_141, 6 },
    { cupcake_demo_ids_142, 6 },
    { cupcake_demo_ids_143, 9 },
    { cupcake_demo_ids_144, 9 },
    { cupcake_demo_ids_145, 9 },
    { cupcake_demo_ids_146, 8 },
    { cupcake_demo_ids_147, 8 },
    { cupcake_demo_ids_148, 8 },
    { cupcake_demo_ids_149, 8 },
    { cupcake_demo_ids_150, 8 },
    { cupcake_demo_ids_151, 8 },
    { cupcake_demo_ids_152, 8 },
    { cupcake_demo_ids_153, 8 },
    { cupcake_demo_ids_154, 8 },
    { cupcake_demo_ids_155, 8 },
    { cupcake_demo_ids_156, 8 },
    { cupcake_demo_ids_157, 3 },
    { cupcake_demo_ids_158, 3 },
    { cupcake_demo_ids_159, 3 },
    { cupcake_demo_ids_160, 3 },
    { cupcake_demo_ids_161, 3 },
    { cupcake_demo_ids_162, 2 },
};

static inline const char *cupcake_demo_sprite_name(unsigned char id) {
    if (id >= CUPCAKE_DEMO_NAME_COUNT)
        return 0;
    return cupcake_demo_name_table[id];
}

#endif
